language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
    - mysql
    - redis

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;
                USE test;
                CREATE TABLE IF NOT EXISTS `user` (
                  `id` INT (11) NOT NULL AUTO_INCREMENT,
                  `name` VARCHAR (20) DEFAULT NULL,
                  `sex` INT (1) NOT NULL DEFAULT '0',
                  `age` INT (1) NOT NULL DEFAULT '0',
                  `description` VARCHAR (240) DEFAULT NULL,
                  PRIMARY KEY (`id`)
                ) ENGINE = INNODB DEFAULT CHARSET = utf8 ;
                CREATE TABLE `user2` (
                  `id` INT (11) NOT NULL AUTO_INCREMENT,
                  `name` VARCHAR (20) DEFAULT NULL,
                  `sex` INT (1) NOT NULL DEFAULT '0',
                  `age` INT (1) NOT NULL DEFAULT '0',
                  `description` VARCHAR (240) DEFAULT NULL,
                  PRIMARY KEY (`id`)
                ) ENGINE = INNODB DEFAULT CHARSET = utf8 ;
                CREATE TABLE `count` (
                  `uid` INT (11) NOT NULL,
                  `fans` INT (1) NOT NULL DEFAULT '0',
                  `follows` INT (1) NOT NULL DEFAULT '0',
                  PRIMARY KEY (`uid`)
                ) ENGINE = INNODB DEFAULT CHARSET = utf8 ;
                CREATE DATABASE IF NOT EXISTS test2;
                USE test2;
                CREATE TABLE IF NOT EXISTS `user` (
                  `id` INT (11) NOT NULL AUTO_INCREMENT,
                  `name` VARCHAR (20) DEFAULT NULL,
                  `sex` INT (1) NOT NULL DEFAULT '0',
                  `age` INT (1) NOT NULL DEFAULT '0',
                  `description` VARCHAR (240) DEFAULT NULL,
                  PRIMARY KEY (`id`)
                ) ENGINE = INNODB DEFAULT CHARSET = utf8 ;'
    - echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - wget https://github.com/redis/hiredis/archive/v0.13.3.tar.gz -O hiredis.tar.gz && mkdir -p hiredis && tar -xf hiredis.tar.gz -C hiredis --strip-components=1 && cd hiredis && sudo make -j$(nproc) && sudo make install && sudo ldconfig && cd ..
  - wget https://github.com/swoole/swoole-src/archive/v2.1.3.tar.gz -O swoole.tar.gz && mkdir -p swoole && tar -xf swoole.tar.gz -C swoole --strip-components=1 && rm swoole.tar.gz && cd swoole && phpize && ./configure --enable-async-redis --enable-coroutine && make -j$(nproc) && make install && echo 'no' | pecl install -f redis && cd -

before_script:
  - composer config -g process-timeout 900 && composer update
  - phpenv config-rm xdebug.ini

script: composer test
